const channels = [
       {
        "id": 1,
        "name": "portoSYNC XXX 1",
        "theme": "adulți",
        "description": "portoSYNC XXX 1",
        "streamUrl": "https://prtsync.ro/prt.mp4",
        "type": "video",
    },
       {
        "id": 2,
        "name": "portoSYNC XXX 2",
        "theme": "adulți",
        "description": "portoSYNC XXX 2",
        "streamUrl": "https://prtsync.ro/prt2.mp4",
        "type": "video",
    },
       {
        "id": 3,
        "name": "portoSYNC XXX 3",
        "theme": "adulți",
        "description": "portoSYNC XXX 3",
        "streamUrl": "https://prtsync.ro/prt3.mp4",
        "type": "video",
    },
       {
        "id": 4,
        "name": "portoSYNC XXX 4",
        "theme": "adulți",
        "description": "portoSYNC XXX 4",
        "streamUrl": "https://prtsync.ro/prt4.mp4",
        "type": "video",
    },
       {
        "id": 5,
        "name": "portoSYNC XXX 5",
        "theme": "adulți",
        "description": "portoSYNC XXX 5",
        "streamUrl": "http://prtsync.ro/prt5.mp4",
        "type": "video",
    },
       {
        "id": 6,
        "name": "portoSYNC XXX 6",
        "theme": "adulți",
        "description": "portoSYNC XXX 6",
        "streamUrl": "https://prtsync.ro/prt6.mp4",
        "type": "video",
    },
       {
        "id": 7,
        "name": "portoSYNC XXX 7",
        "theme": "adulți",
        "description": "portoSYNC XXX 7",
        "streamUrl": "https://prtsync.ro/prt7.mp4",
        "type": "video",
    },
       {
        "id": 8,
        "name": "portoSYNC XXX 8",
        "theme": "adulți",
        "description": "portoSYNC XXX 8",
        "streamUrl": "https://prtsync.ro/prt8.mp4",
        "type": "video",
    },
       {
        "id": 9,
        "name": "portoSYNC XXX 9",
        "theme": "adulți",
        "description": "portoSYNC XXX 9",
        "streamUrl": "https://prtsync.ro/prt9.mp4",
        "type": "video",
    },
       {
        "id": 10,
        "name": "portoSYNC XXX 10",
        "theme": "adulți",
        "description": "portoSYNC XXX 10",
        "streamUrl": "https://prtsync.ro/prt10.mp4",
        "type": "video",
    },
       {
        "id": 11,
        "name": "portoSYNC XXX 11",
        "theme": "adulți",
        "description": "portoSYNC XXX 11",
        "streamUrl": "https://prtsync.ro/prt11.mp4",
        "type": "video",
    },
       {
        "id": 12,
        "name": "portoSYNC XXX 12",
        "theme": "adulți",
        "description": "portoSYNC XXX 12",
        "streamUrl": "http://portosync.eu/prt12.mp4",
        "type": "video",
    },
       {
        "id": 13,
        "name": "portoSYNC XXX 13",
        "theme": "adulți",
        "description": "portoSYNC XXX 13",
        "streamUrl": "https://prtsync.ro/prt13.mp4",
        "type": "video",
    },
       {
        "id": 14,
        "name": "portoSYNC XXX 14",
        "theme": "adulți",
        "description": "portoSYNC XXX 14",
        "streamUrl": "https://prtsync.ro/prt14.mp4",
        "type": "video",
    },
       {
        "id": 15,
        "name": "portoSYNC XXX 15",
        "theme": "adulți",
        "description": "portoSYNC XXX 15",
        "streamUrl": "https://prtsync.ro/prt15.mp4",
        "type": "video",
    },
       {
        "id": 16,
        "name": "portoSYNC XXX 16",
        "theme": "adulți",
        "description": "portoSYNC XXX 16",
        "streamUrl": "https://prtsync.ro/prt16.mp4",
        "type": "video",
    },
       {
        "id": 17,
        "name": "portoSYNC XXX 17",
        "theme": "adulți",
        "description": "portoSYNC XXX 17",
        "streamUrl": "https://prtsync.ro/prt17.mp4",
        "type": "video",
    },
       {
        "id": 18,
        "name": "portoSYNC XXX 18",
        "theme": "adulți",
        "description": "portoSYNC XXX 18",
        "streamUrl": "https://prtsync.ro/prt18.mp4",
        "type": "video",
    },
       {
        "id": 19,
        "name": "portoSYNC XXX 19",
        "theme": "adulți",
        "description": "portoSYNC XXX 19",
        "streamUrl": "https://prtsync.ro/prt19.mp4",
        "type": "video",
    },
       {
        "id": 20,
        "name": "portoSYNC XXX 20",
        "theme": "adulți",
        "description": "portoSYNC XXX 20",
        "streamUrl": "https://prtsync.ro/prt20.mp4",
        "type": "video",
    },
       {
        "id": 21,
        "name": "portoSYNC XXX 21",
        "theme": "adulți",
        "description": "portoSYNC XXX 21",
        "streamUrl": "https://prtsync.ro/prt21.mp4",
        "type": "video",
    },
       {
        "id": 22,
        "name": "portoSYNC XXX 22",
        "theme": "adulți",
        "description": "portoSYNC XXX 22",
        "streamUrl": "https://prtsync.ro/prt22.mp4",
        "type": "video",
    },
       {
        "id": 23,
        "name": "portoSYNC XXX 23",
        "theme": "adulți",
        "description": "portoSYNC XXX 23",
        "streamUrl": "https://prtsync.ro/prt23.mp4",
        "type": "video",
    },
       {
        "id": 24,
        "name": "portoSYNC SEX",
        "theme": "adulți",
        "description": "portoSYNC SEX",
        "streamUrl": "http://prtsync.ro/xxx.mp4",
        "type": "video",
    },
       {
        "id": 25,
        "name": "portoSYNC SEX 2",
        "theme": "adulți",
        "description": "portoSYNC SEX 2",
        "streamUrl": "http://prtsync.ro/xxx2.mp4",
        "type": "video",
    },
       {
        "id": 26,
        "name": "portoSYNC SEX 3",
        "theme": "adulți",
        "description": "portoSYNC SEX 3",
        "streamUrl": "http://prtsync.ro/prn/prn.mp4",
        "type": "video",
    },
       {
        "id": 27,
        "name": "portoSYNC SEX 4",
        "theme": "adulți",
        "description": "portoSYNC SEX 4",
        "streamUrl": "http://prtsync.ro/porn/porn.mp4",
        "type": "video",
    },
       {
        "id": 28,
        "name": "portoSYNC SEX 5",
        "theme": "adulți",
        "description": "portoSYNC SEX 5",
        "streamUrl": "http://prtsync.ro/porno/porno.mp4",
        "type": "video",
    },
       {
        "id": 29,
        "name": "portoSYNC SEX 6",
        "theme": "adulți",
        "description": "portoSYNC SEX 6",
        "streamUrl": "http://prtsync.ro/prn2/prn2.mp4",
        "type": "video",
    },
       {
        "id": 30,
        "name": "portoSYNC SEX 7",
        "theme": "adulți",
        "description": "portoSYNC SEX 6",
        "streamUrl": "http://prtsync.ro/sex/sex.mp4",
        "type": "video",
    },
       {
        "id": 31,
        "name": "portoSYNC SEX 8",
        "theme": "adulți",
        "description": "portoSYNC SEX 8",
        "streamUrl": "http://prtsync.ro/sex2/sex2.mp4",
        "type": "video",
    },
]